
import random
print("WELCOME To SMART PARKING\n")
GREETING_KEYWORDS = ["hello", "hi", "greetings", "hey", "what's up","good morning","good evening","good afternoon"]
GREETING_RESPONSES = ["Nice to meet you","It's a pleasure to see you","Sup bro", "hey","How can I help you with?"]
PARKING_KEYWORDS = ["Tell me places to park","where can i park?","what are the parking spaces","need a parking space","need to park my vehicle"]
PARKING_RESPONSES=["There are 5 parking lots-->\n1.Silver Jubilee Tower(SJT)\n2.Technology Tower(TT)\n3.TT backside\n4.Lassi House\n5.Gate no.2\n"]
PARKING_SLOTS=["1.Silver Jubilee Tower(SJT)","2.TechNology Tower","3.TT backside","4.Lassi House","5.Gate no.2"]
PARKING_LEFT=[5,6,3,9,2]
def check_for_greeting(sentence):
    if sentence.lower() in GREETING_KEYWORDS:
        print(random.choice(GREETING_RESPONSES))
def parkinglot(sentence):
     if sentence.lower() in PARKING_KEYWORDS:       
         print(random.choice(PARKING_RESPONSES))
def pay(t,num):
    print("Total price = "+str(n*t*30))
    
         
 

sentence=input()
check_for_greeting(sentence)
sentence2=input()
parkinglot(sentence2)
    
    num=int(input("\n How many number of cars?"))
    print(" Available Parking spaces - \n")
    c=0
    for i in range(len(PARKING_LEFT)):
        if(PARKING_LEFT[i]>=num):
            print(PARKING_SLOTS[i]+"\n")
            c=c+1
    n=int(input("Choose the option!!"))
    t=int(input("Please state the approximate duration of your stay in hours"))
    
        
        
    print("\n\nPLease collect the token generated by the machine")
    print("------------------------------------------\n")
    print(PARKING_SLOTS[n])
    print()
    print("Number of cars- "+str(num))
    print("Total time "+str(t)+"Hrs")
    print()
    import datetime
    currentDT = datetime.datetime.now()
    print (currentDT.strftime("%Y-%m-%d %H:%M:%S"))
    print (currentDT.strftime("%Y/%m/%d"))
    print (currentDT.strftime("%H:%M:%S"))
    print (currentDT.strftime("%I:%M:%S %p"))
    print (currentDT.strftime("%a, %b %d, %Y"))
    print()
    pay(t,num)