from nltk.chat.util import Chat, reflections
pairs = [
    [
        r"my name is (.*)",
        ["Hello %1, How are you today ?",]
    ],
     [
        r"what is your name ?",
        ["My name is qwerty and I'm a chatbot ",]
    ],
    [
        r"how are you ?",
        ["I'm doing good\nHow about You ?",]
    ],
    [
        r"sorry (.*)",
        ["Its alright","Its OK, never mind",]
    ],
    [
        r"i'm (.*) doing good",
        ["Nice to hear that","Alright :)",]
    ],
    [
        r"hi|hey|hello|wassup|good morning|good evening|good afternoon",
        ["Hello", "Hey there","Nice to meet you","It's a pleasure to see you","Sup bro","How can I help you with?",]
    ],
    [
        r"Tell me places to park|where can i park|what are the parking spaces|need a parking space|(.*) need (.*) park ",
        ["There are 5 parking lots-->\n1.Silver Jubilee Tower(SJT)\n2.Technology Tower(TT)\n3.TT backside\n4.Lassi House\n5.Gate no.2\n",]
    ],
    [
        r"quit|bye|see you",
        ["Bye take care. See you soon :) ","It was nice talking to you. See you soon :)"]
],
]
def chatty():
    print("Hi, I'm Chatty and I chat alot ;)\nPlease type lowercase English language to start a conversation. Type quit to leave ") #default message at the start
    chat = Chat(pairs, reflections)
    chat.converse()
def pay(t,num):
    print("Total price = "+str(n*t*30))
if __name__ == "__main__":
    chatty()
    PARKING_LEFT=[5,6,3,9,2]
    PARKING_SLOTS=["1.Silver Jubilee Tower(SJT)","2.TechNology Tower","3.TT backside","4.Lassi House","5.Gate no.2"]
    num=int(input("\n How many number of cars?"))
    print(" Available Parking spaces - \n")
    c=0
    for i in range(len(PARKING_LEFT)):
        if(PARKING_LEFT[i]>=num):
            print(PARKING_SLOTS[i]+"\n")
            c=c+1
    n=int(input("Choose the option!!"))
    t=int(input("Please state the approximate duration of your stay in hours"))
    
        
        
    print("\n\nPLease collect the token generated by the machine")
    print("------------------------------------------\n")
    print(PARKING_SLOTS[n])
    print()
    print("Number of cars- "+str(num))
    print("Total time "+str(t)+"Hrs")
    print()
    import datetime
    currentDT = datetime.datetime.now()
    print (currentDT.strftime("%Y-%m-%d %H:%M:%S"))
    print (currentDT.strftime("%Y/%m/%d"))
    print (currentDT.strftime("%H:%M:%S"))
    print (currentDT.strftime("%I:%M:%S %p"))
    print (currentDT.strftime("%a, %b %d, %Y"))
    print()
    pay(t,num)